name: Package

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      docker_repo:
        required: true
        type: string
      container_port:
        required: false
        default: 80
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Docker login
      -
        name: Login To Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build Docker file and push to docker hub
      -
        name: Build And Package
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.docker_repo }}
      
      # Display new image tag
      -
        name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
  deploy:
    runs-on: [self-hosted,deployer]
    needs: build
    
    steps:
    
    # Docker login
    -
      name: Login To Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Update and deploy changes
    -
      name: Deploy Changes
      run: |
        docker image pull ${{ inputs.docker_repo }} 2>&1
        docker kill ${{ inputs.domain }} 2>&1
        docker container rm ${{ inputs.domain }} 2>&1
        docker run -d --name ${{ inputs.domain }} -e VIRTUAL_HOST=${{ inputs.domain }} -e VIRTUAL_PORT=${{ inputs.container_port }} -e LETSENCRYPT_HOST=${{ inputs.domain }} ${{ inputs.docker_repo }}
