name: Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Docker login
      -
        name: Login To Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build Docker file and push to docker hub
      -
        name: Build And Package
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO }}
      
      # Display new image tag
      -
        name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
  deploy:
    runs-on: [self-hosted,deployer]
    needs: build
    
    steps:
    -
      name: Deploy Changes
      run: |
        echo ${{ secrets.DOCKER_REPO }}
        echo ${{secrets.DOMAIN}}
